from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from datetime import datetime

import io
import os


# =========================
# 注册中文字体
# =========================

FONT_PATH = "C:/Windows/Fonts/msyh.ttc"

if os.path.exists(FONT_PATH):

    pdfmetrics.registerFont(
        TTFont(
            "MicrosoftYaHei",
            FONT_PATH
        )
    )

    FONT_NAME = "MicrosoftYaHei"

else:

    FONT_PATH = "C:/Windows/Fonts/simhei.ttf"

    pdfmetrics.registerFont(
        TTFont(
            "SimHei",
            FONT_PATH
        )
    )

    FONT_NAME = "SimHei"


# =========================
# PDF生成
# =========================

def create_pdf(
    result,
    report_text,
    sample_id,
    fig
):

    pdf_name = (
        f"Sample_{sample_id}_Report.pdf"
    )

    doc = SimpleDocTemplate(
        pdf_name,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm
    )

    styles = getSampleStyleSheet()

    chinese_style = ParagraphStyle(
        name="Chinese",
        parent=styles["BodyText"],
        fontName=FONT_NAME,
        fontSize=11,
        leading=18
    )

    heading_style = ParagraphStyle(
        name="Heading",
        parent=styles["Heading2"],
        fontName=FONT_NAME
    )

    title_style = ParagraphStyle(
        name="TitleCN",
        parent=styles["Title"],
        fontName=FONT_NAME
    )

    content = []

    # =========================
    # 标题
    # =========================

    content.append(
        Paragraph(
            "超导薄膜Tc分析报告",
            title_style
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # =========================
    # 基本信息
    # =========================

    content.append(
        Paragraph(
            f"样品编号：Sample {sample_id}",
            chinese_style
        )
    )

    content.append(
        Paragraph(
            f"生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M')}",
            chinese_style
        )
    )

    content.append(
        Spacer(1, 10)
    )

    # =========================
    # 参数结果
    # =========================

    content.append(
        Paragraph(
            "Tc参数分析结果",
            heading_style
        )
    )

    content.append(
        Spacer(1, 6)
    )

    metrics = [

        f"Tc = {result['Tc']:.3f} K",

        f"Tc_onset = {result['Tc_onset']:.3f} K",

        f"Tc_end = {result['Tc_end']:.3f} K",

        f"Transition Width = {result['Width']:.3f} K",

        f"Noise Level = {result['NoiseLevel']:.4f}",

        f"Transition Strength = {result['TransitionStrength']:.3f}",

        f"Quality Score = {result['QualityScore']:.1f}"
    ]

    for item in metrics:

        content.append(
            Paragraph(
                item,
                chinese_style
            )
        )

    content.append(
        Spacer(1, 10)
    )

    # =========================
    # 曲线图
    # =========================

    content.append(
        Paragraph(
            "R-T曲线",
            heading_style
        )
    )

    content.append(
        Spacer(1, 6)
    )

    img_buffer = io.BytesIO()

    fig.savefig(
        img_buffer,
        format="png",
        dpi=300,
        bbox_inches="tight"
    )

    img_buffer.seek(0)

    content.append(
        Image(
            img_buffer,
            width=15 * cm,
            height=9 * cm
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # =========================
    # AI分析
    # =========================

    content.append(
        Paragraph(
            "AI科研分析结果",
            heading_style
        )
    )

    content.append(
        Spacer(1, 6)
    )

    # 清理 markdown 标记
    report_text = report_text.replace(
        "#",
        ""
    )

    report_text = report_text.replace(
        "\n",
        "<br/>"
    )

    content.append(
        Paragraph(
            report_text,
            chinese_style
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by AI-Superconducting-Tc-Analysis-Platform",
            chinese_style
        )
    )

    doc.build(content)

    return pdf_name